sissefail = input("Palun sisesta sisestus faili nimi: ")
väljafail = input("Palun sisesta välja faili nimi: ")
f1 = open(sissefail)
f2 = open(väljafail, "w")
asendamised = f1.read().count("Hello")
f2.write(f1.read().replace("Hello", "Tere"))
print(asendamised)
f1.close()
f2.close()