a = input('Sisestage lähtefaili nimi (lisage ".txt"): ')
b = input('Sisestage sihtfaili nimi (lisage ".txt"): ')
fail_a = open(a, 'r')
x = fail_a.read()
fail_b = open(b, 'w')
sisu = x.replace('Hello', 'Tere')
fail_b.write(sisu)
loendus = int(sisu.count('Tere'))
fail_a.close()
fail_b.close()
print('Tehti', loendus, 'asendust.')