fail = input('Lähtefaili nimi: ')
fail_uus = input('Sihtfaili nimi: ')
f = open(fail, 'r')
sisu = f.read()
a = open(fail_uus, 'w' )
c = sisu.replace('Hello', 'Tere')
b = a.write(c)
asendused = c.count('Tere')
print('Tehti '+ str(asendused) +' asendamist.')