Lahtefail = open(input("Sisestage lahtefaili nimi: "))
Sihtfail = str(input("Sisestage siia sihtfaili nimi: "))
Lahtefail = Lahtefail.read()
Asendatud = Lahtefail.count("Hello")
Sihttekst = Lahtefail.replace("Hello", "Tere")
Sihtfail = open(str(Sihtfail + ".txt"), "w")
Sihtfail.write(Sihttekst)
Sihtfail.close()
print("Tehti " + str(Asendatud) + " asendamist.")
