fail1=input("Sisestage palun esimese faili nimi: ")
fail2=input("Sisestage palun teise faili nimi: ")
a=open(fail1,"r")
sisu=a.read()
print(sisu)
mitu=sisu.count("Hello")
b=open(fail2,"w")
b.write(sisu.replace("Hello","Tere"))
a.close()
b.close()
print("Tehti",mitu,"asendust")