algneFail = input('Lähtefaili nimi: ')
uusFail = input('Sihtfaili nimi: ')
f = open(algneFail)
sisu = f.read()
asendus = sisu.replace('Hello','Tere')
f.close()
f = open(uusFail, "w")
f.write(asendus)
f.close()
print(sisu.count('Hello'))