f_olemas = input("Lähtefaili nimi: ")
f_siht = input("Sihtfaili nimi: ")
f = open(f_olemas)
faili_sisu = f.read()
f.close()
asendused = faili_sisu.count("Hello")
uus_sisu = faili_sisu.replace("Hello", "Tere")
f_new = open(f_siht, "w")
f_new.write(uus_sisu + "\n")
f_new.close()
print("Lähtefaili nimi:", f_olemas)
print("Sihtfaili nimi:", f_siht)
print("Tehti", asendused, "asendamist.")
