fail = input("Sisestage esimese faili nimi: ")
fail2 = input("Sisestage teise faili nimi: ")
x = open(fail, "r")
y = x.read()
print(y)
z = y.count("Hello")
h = open(fail2, "w")
h.write(y.replace("Hello", "Tere"))
x.close()
h.close()
print("Tehti", z, "asendust")