a=input("Lähtefaili nimi: ")
b=input("Sisesta sihtfaili nimi: ")
f=open(a)
faili_sisu=f.read()
f=open(b, "w")
f.write(faili_sisu.replace("Hello", "Tere"))
f.close()
c=faili_sisu.count("Hello")
print(c)
