filein = input("Sisestage algfail: ")
fileout = input("Sisestage l]ppfail: ")
fin = open(filein)
fins = fin.read()
fouts = fins.replace('Hello', 'Tere')
c = fins.count('Hello')
fin.close()
fout = open(fileout, 'w')
fout.write(fouts)
fout.close()
print('Tehti ' + str(c) + ' asendamist.')