leht = input("sisestage fail tõlkimiseks:  ")
leht2 = input("sisestage fail kuhu tõlkida:  ")
f = open(leht)
inglise = f.read()
f.close()
eesti = inglise.replace('Hello', 'Tere')
teisendus = inglise.count('Hello')
f = open(leht2, "w")
f.write(eesti + "\n")
f.close()
print(teisendus)