eesnimi = input("Sisesta oma eesnimi ")
eesnimi = eesnimi.upper()
perekonnanimi = input("Sisesta oma perekonnanimi ")
perekonnanimi = perekonnanimi.upper()
print((eesnimi  + "." +  perekonnanimi).lower())
