lähtefail = input("Sisestage lähtefaili nimi: ")
sihtfail = input("Sisestage sihtfaili nimi: ")
f = open(lähtefail)
faili_sisu = f.read()
asendus = faili_sisu.replace("Hello", "Tere")
print(asendus)
f.close()
x = open(sihtfail, "w")
x.write (asendus)
x.close()
asenduste_arv = faili_sisu.count ("Hello")
print("Asenduste arv on:", asenduste_arv)
