fail1 = open(input("Lähtefaili nimi: "))
failisisu1 = fail1.read()
fail2 = open(input("Sihtfaili nimi: "), "a+")
fail2.write(failisisu1.replace('Hello', 'Tere'))
failisisu2 = fail2.read()
asendused = failisisu2.count("Tere") 
print("Asendusi tehti ", str(asendused))
fail1.close()
fail2.close()
