inglise_fail= input('sisesta inglisekeelse faili nimi: ')
eesti_fail= input('sisesta eestikeelse faili nimi: ')
f1= open(inglise_fail, "r")
f2= open(eesti_fail, "w")
f2.write (f1.read().replace('Hello','Tere'))
tekst= f1.read()
asendused= tekst.count ("Hello")
print('Programm tegi',asendused,'asendust tekstis')
f1.close()
f2.close()