eesnimi = input("Sisestage oma eesnimi: ")
osa1 = eesnimi.lower()
perenimi = input("Sisestage oma perenimi: ")
osa2 = perenimi.lower()
kasutajanimi = (osa1 + '.' + osa2)
print("Teie kasutajanimi on", kasutajanimi)