tõlgitav = open(input("Sisestage tõlgitava faili nimi: "))
tõlge = input("Kuidas soovite tõlgitud dokumenti nimetada? ")
tõlgitavtekst = tõlgitav.read()
asendatud = tõlgitavtekst.count("Hello")
tõlketekst = tõlgitavtekst.replace("Hello", "Tere")
tõlgitav.close()
tõlge = open(str(tõlge + ".txt"), "w")
tõlge.write(tõlketekst)
tõlge.close()
print("Sõna \"Hello\" asendati teie failis " + str(asendatud) + " Korda sõnaga \"Tere\".")