r=input("Sisesta üks olemas olev tekstifail: ")
c=open(r)
t=c.read ()
b=t.count("Hello")
c.close()
s=input("Sisesta üks uue tekstifaili nimi: ")
f=open(s,"w")
g=t.replace("Hello","Tere")
f.write(g)
f.close()
print('Tehti',b,'asendamist')