lf=input("Lähtefaili nimi: ")
sf=input("Sihtfaili nimi: ")
f=open(lf)
inglise_fail=f.read()
eesti_fail=(inglise_fail.replace('Hello','Tere'))
e=open(sf, "w")
e.write(eesti_fail)
a=(eesti_fail.count('Tere'))
print('Tehti '+str(a) +' asendamist:')
print(inglise_fail)
print(eesti_fail)
e.close()