esimenef = input("Sisestage siseneva olemasoleva faili nimi: ")
teinef = input("Sisestage väljuva faili nimi: ")
f = open(esimenef)
fsisu = f.read()
f.close()
asendusi = fsisu.count("Hello")
fsisu = fsisu.replace("Hello","Tere")
f = open(teinef, "w")
f.write(fsisu)
f.close()
print(f"Teostati {asendusi} asendust")