fail = open("kinganumbrid.txt")
rida = float (fail.readline(). replace ("\n", " "))
pikkus = 2/3 * (rida - 2)
ymardatud = round (pikkus)
print (ymardatud)
rida2 = float (fail.readline(). replace ("\n", " "))
pikkus2 = 2/3 * (rida2 - 2)
ymardatud2 = round (pikkus2)
print (ymardatud2)
rida3 = float (fail.readline(). replace ("\n", " "))
pikkus3 = 2/3 * (rida2 - 2)
ymardatud3 = round (pikkus3)
print (ymardatud3)
rida4 = float (fail.readline(). replace ("\n", " "))
pikkus4 = 2/3 * (rida4 - 2)
ymardatud4 = round (pikkus4)
print (ymardatud4)
