lf = input("Sisesta lähtefaili nimi: ")
sf = input("Sisesta sihtfaili nimi: ")
f1 = open(str(lf))
f2 = open(str(sf), "w")
fs= f1.read()
mh = fs.count("Hello")
f1.close()
f2.write(fs.replace("Hello", "Tere"))
f2.close()
print("Tehti " + str(mh) + " asendamist")
