esimenefail=input("Mis failist te loete? ")
teinefail=input("Mis faili te kirjutate? ")
f=open(str(esimenefail))
sisu=f.read()
f.close()
pahandus=sisu.count("Hello")
sisu=sisu.replace("Hello","Tere")
f=open(str(teinefail), "x")
f.write(sisu)
print("Tegin", int(pahandus), "asendamist.")
f.close()