lähtefail = str(input("Lähtefaili nimi(.txt lõppu): "))
sihtfail = str(input("Sihtfaili nimi(.txt lõppu): "))
f = open(lähtefail, "r")
tekst = f.read()
asendusiVäike = tekst.count("hello")
asendusiSuur = tekst.count("Hello")
tekst = tekst.replace("hello", "tere")
tekst = tekst.replace("Hello", "Tere")
c = open(sihtfail, "w")
c.write(str(tekst))
c.close()
asendusiKokku = str(asendusiSuur + asendusiVäike)
print("Tehti "+ asendusiKokku +" asendust.")