fail1 = input("Sisesta lähtefail: ")
fail2 = input("Sisesta sihtfail: ")
f = open('fail1')
faili_sisu = f.read()
f.close()
t = open("fail2", "w")
t.write(faili_sisu)
print("Failis tehti", faili_sisu.count('Hello'), "asendust.")
'faili_sisu'.replace('Hello', 'Tere')
t.close()