fail1=input("Sisesta esimese faili nimi: ")
fail2=input("Sisesta teise faili nimi: ")
f=open(fail1)
g=open(fail2, "w")
faili_sisu=f.read()
tekst=faili_sisu.replace('hello','tere')
tekst=tekst.replace('Hello','Tere')
g.write(tekst)
g.close()
a=faili_sisu.count("Hello")
b=faili_sisu.count("hello")
f.close()
print("Tehti ", a+b, " asendamist.")