inglise=input("Sisesta lähtefaili nimi: ")
eesti=input("Sisesta sihtfaili nimi: ")
f=open(inglise)
faili_sisu=f.read()
asendatud=faili_sisu.replace("Hello", "Tere")
f.close()
g=open(eesti, "w")
g.write(asendatud)
g.close()
print("Tehti " + str(faili_sisu.count("Hello")) + " asendamist.")