fail1 = input("Lähtefaili nimi: ")
fail2 = input("Sihtfaili nimi: ")
f1= open(fail1)
inglise_sisu = f1.read()
f2 = open(fail2, "w")
f2.write (inglise_sisu.replace("Hello", "Tere"))
inglise_sisu.count ("Tere")
f2.close()
f3 = open(fail2)
eesti_sisu = f3.read()
number = eesti_sisu.count ("Tere")
print("Muudatusi: " + str(number))
