f1=open(input('Lähtefaili nimi: '))
f2=open(input('Sihtfaili nimi: '),"w")
f1_sisu=f1.read()
arv=f1_sisu.count('Hello')
f1_sisu_asendus=f1_sisu.replace('Hello','Tere')
f2.write(f1_sisu_asendus)
print(arv)
f1.close()
f2.close()