efail = input("Sisesta esimese faili nimi: ")
tfail = input("Sisesta teise faili nimi: ")
a = open(efail, "r")
b = open(tfail, "w")
sisu = a.read()
c = sisu.count("Hello")
b.write(sisu.replace("Hello", "Tere"))
print("Tehti " , c ,  "asendamist.")
b.close()
d = open(tfail, "r")
print("Faili", tfail , "sisu:" ,  "\n" , d.read())
a.close()
d.close()