f = open(input("Lähtefaili nimi:"))
sisu = f.read()
c=str(sisu.count("Hello"))
sisu=sisu.replace("Hello", "Tere")
f.close()
a=(input("Sihtfaili nimi:"))
g=open(a, "w")
g.write(sisu)
print("Tehti " + c + " asendamist")
g.close()
