esialgne_tekstifail = input(print("Kirjuta siia esialgse faili nimi."))
uus_tekstifail = input(print("Kirjuta siia uue faili nimi."))
Hello_txt = open(str(esialgne_tekstifail), 'r')
faili_sisu = Hello_txt.read()
print(faili_sisu)
faili_sisu2 = faili_sisu.replace("Hello", "Tere")
print(faili_sisu2)
uus_fail = open(str(uus_tekstifail), "w")
uus_fail.write(faili_sisu2)
uus_fail.close()
Hello_txt.close()
Hello_txt = open(str(esialgne_tekstifail), 'r')
faili_sisu3 = Hello_txt.read()
Tere_txt = open(str(uus_tekstifail), "r")
faili_sisu4 = Tere_txt.read()
print(int(faili_sisu4.count("Tere"))-int(faili_sisu.count("Tere")))