inglise = input("Lähtefaili nimi: ")
eesti = input("Sihtfaili nimi: ")
f = open(inglise)
faili_sisu = f.read()
f.close()
faili_sisu_e = faili_sisu.replace("Hello","Tere")
f2 = open(eesti, 'w')
f2.write(faili_sisu_e)
f2.close()
print("Tehti", faili_sisu_e.count("Tere"), "asendamist.")
