fin= input("Lähtefaili nimi: ")
fin=open(fin, "r")
data=fin.read()
data=data.replace("Hello", "Tere" )
fin.close()
fin= input("Sihtfaili nimi: ")
fin = open(fin, "w")
fin.write(data)
a=fin.read()
a=fin.count("Hello")
print("Tehti " + str(a) + " asendamist.")
fin.close()