a = input ("Lähtefaili nimi ")
b = input ("Sihtfaili nimi ")
c = open (a)
faili_sisu = c.read ()
print (faili_sisu)
d = open (b, "w")
e = faili_sisu.replace ("Hello", "Tere")
d.write (e)
print (faili_sisu.count ("Hello"))
d.close ()
c.close ()
