file1 = input("Lähtefaili nimi: ")
file2 = input("Sihtfaili nimi: ")
f = open(file1, "r")
test = f.read()
print("Tehti "+str(test.count("Hello"))+" asendamist.")
text = test.replace("Hello","Tere")
w = open(file2, "w")
print(text + "appii")
w.write(text)
w.close()