filein=input("Lähtefaili nimi:")
fileout=input("Sihtfaili nimi:")
f = open(filein,"r")
filedata = f.read()
f.close()
tere = filedata.replace("Hello", "Tere")
f = open(fileout, "w")
f.write(tere)
f.close()
print(filedata.count("Hello"))