inglise=input("Lähtefaili nimi:")
eesti=input("Sihtfaili nimi:")
algne=open(inglise,'r')
uus=open(eesti,"w")
tekst=algne.read()
teisendused=tekst.count("Hello")
uus.write(tekst.replace("Hello","Tere"))
algne.close()
uus.close()
print(teisendused)