algfail=input("Sisesta algfaili nimi: ")
uus_fail=input("Sisesta uue faili nimi: ")
f=open(algfail)
algfail_sisu=f.read()
f2=open(uus_fail, 'w')
f2.write((algfail_sisu).replace('Hello','Tere'))
f.close()
f2.close()
f=open(uus_fail)
eesti_sisu=f.read()
asendused=algfail_sisu.count('Hello')
print('Tehti '+str(asendused)+' asendust.')
f.close()