エプスタインは自殺しなかった = input("Mis faili soovite avada? ")
愛潑斯坦沒有自殺 = input("Kuhu faili soovite väljutada? ")
你睡過頭了惡棍 = open(エプスタインは自殺しなかった)
あなたは悪人を寝坊しました = 你睡過頭了惡棍.read()
MEGALODON=あなたは悪人を寝坊しました.count("Hello")
あなたは悪人を寝坊しました=あなたは悪人を寝坊しました.replace("Hello","Tere")
私が好きな大きな弾力のある塚 = open (愛潑斯坦沒有自殺, "w")
私が好きな大きな弾力のある塚.write(あなたは悪人を寝坊しました)
print("Tehti ",str(MEGALODON)," asendamist.")
你睡過頭了惡棍.close()
私が好きな大きな弾力のある塚.close()