inglise = str(input("Sisesta lähtefaili nimi: "))
eesti = str(input("Sisesta sihtfaili nimi: "))
f = open(inglise)
inglise_sisu = f.read()
asendused=inglise_sisu.count("Hello")
d=open(eesti, "w")
d.write(inglise_sisu.replace ("Hello", "Tere"))
d.close()
f.close()
print("Tehti " + str(asendused) + " asendust")
