fail1 = input("Sisesta esimene failinimi: ")
fail2 = input("Sisesta teine failinimi: ")
f = open(fail1)
tekst = f.read()
f.close()
f = open(fail2, "w")
tekst2 = tekst.replace("Hello", "Tere")
f.write(tekst2)
f.close()
count = tekst.count("Hello")
print ("Tehti",count, "asendamist.")
