lähtefail = input("Lähtefaili nimi: ")
sihtfail = input("Sihtfaili nimi: ")
LÄHTEFAIL = open(lähtefail, "r")
SIHTFAIL = open(sihtfail, "w")
tekst = LÄHTEFAIL.read()
asendusi = tekst.count("Hello")
uus_tekst = tekst.replace("Hello","Tere")
SIHTFAIL.write(uus_tekst)
SIHTFAIL.close()
LÄHTEFAIL.close()
print("Tehti", asendusi, "asendamist.")